[package]
name = 'web_api_derive'
version = '0.1.0'
authors = ['Mdrokz <mohammadmunshi@gmail.com>']
edition = '2018'

[lib]
proc-macro = true

[dependencies]
syn = '1.0.14'
quote = '1.0.2'
postgres-types = '0.1.0'
